### ISSUE TITLE
Setting diagonal values in the affinity matrix

### ISSUE THREAD

**Issue by JoseAndresMR** [mit-acl/clipper#11]
Hi,

Thanks a lot for your great work! I have a question regarding the diagonal values in the affinity matrix. The function CLIPPER::setMatrixData sets to zero all of the values in the diagonal entries of M and C matrices. However, in the paper it is explicated that those values `measure the similarity of the data points that association`. As I have that information, I'd like to be able to use it.

I have tried commenting those lines and making clipper work with my forced values in M_ and C_. However, I'm getting wrong results. Could you please let me know how should I set those values? Thanks in advance!

**Comment by plusk01** [comment]
Hi @JoseAndresMR thanks for the question.

Yes, the latest code is heavily optimized to take advantage of sparsity and so the diagonal elements of M are hard-coded to be 1. It may be easiest to try running CLIPPER with your data in MATLAB (https://github.com/mit-acl/clipper/blob/main/matlab/clipper.m).

As a quick example of how the c++ code is optimized and assumes 1s on the diagonal of M (and C), consider

https://github.com/mit-acl/clipper/blob/b66b329fe0cf51ee2fdc6f2812612d2b16fc6487/src/clipper.cpp#L170

By assuming that `M = (M_ + I)`, we can write `M*u = M_*u + u`. This simple trick saves memory and further reduces the number of elements in the sparse matrix `M_`. It has the greatest impact in calculations involving the gradient, e.g., 

https://github.com/mit-acl/clipper/blob/b66b329fe0cf51ee2fdc6f2812612d2b16fc6487/src/clipper.cpp#L184

If you really can't use MATLAB to test your data, you might consider using an older (slower) version of the code: https://github.com/mit-acl/clipper/blob/f4e67ec575a2d4d505971ac2ab15fd2208b3a193/src/find_dense_cluster.cpp

In my experience I have seen more benefit in preprocessing the initial set of putative matches -- i.e., using the weights that you would have put on the diagonal to threshold which matches are no good, allowing you to throw them out early on, thus speeding up and making the consistent measurement selection step easier.

**Comment by plusk01** [comment]
closing for now, but feel free to re-open / continue the discussion
