### ISSUE TITLE
Orthogonal projected gradient ascent

### ISSUE THREAD

**Issue by qiaozhijian** [mit-acl/clipper#12]
Hello~Thanks for your open source work.

You mentioned in your paper, orthogonal projected gradient ascent are applied. However, in this code https://github.com/mit-acl/clipper/blob/e1015411ebac4940039e07f8efb0e5c391cc1ade/src/clipper.cpp#L179, it seems to be standard gradient ascent. Am I right?

**Comment by plusk01** [comment]
Hi @qiaozhijian, thanks for the question.

It is correct that in our original paper we used orthogonal projected gradient ascent. However, after implementing the algorithm for a multi-robot frame alignment experiment, we determined that the extra computational cost of projecting the gradient onto the tangent space of the unit sphere (i.e., the _orthogonal_ part) did not significantly improve accuracy. The goal of the orthogonal projection is to allow the algorithm to take fewer, more meaningful steps. However, this did not seem to be the case. Note that we did not explore how to optimize the code for this case and it may be worth running tests on a variety of different datasets to understand this deeper.

You can find the orthogonal projection in the MATLAB code, commented out (https://github.com/mit-acl/clipper/blob/main/matlab/clipper.m#L107) or at this commit (f4e67ec575a2d4d505971ac2ab15fd2208b3a193) of the c++ https://github.com/mit-acl/clipper/blob/f4e67ec575a2d4d505971ac2ab15fd2208b3a193/src/find_dense_cluster.cpp#L102


However, note that we are still using *projected* gradient ascent where we project onto the positive orthant of the unit sphere after taking a step

https://github.com/mit-acl/clipper/blob/b66b329fe0cf51ee2fdc6f2812612d2b16fc6487/src/clipper.cpp#L200-L202

**Comment by plusk01** [comment]
closing for now, feel free to re-open / continue the discussion
