### ISSUE TITLE
How to get the RT Matrix?

### ISSUE THREAD

**Issue by dongyu728** [mit-acl/clipper#14]
From the C++ code, I don’t seem to see how to get the rotation and translation matrix. How can I get this correspondence ?
Thank you so much！

**Comment by plusk01** [comment]
Hi @dongyu728, once CLIPPER provides the correspondences, you are free to use any method for estimation the transformation. Typically, this will be a least squares method. For example, in C++ you could use [`Eigen::umeyama`](https://eigen.tuxfamily.org/dox/group__Geometry__Module.html#gab3f5a82a24490b936f8694cf8fef8e60) or in python you could implement Arun's method, like so:

```python
def arun(q, p):
    """Arun's Method
    Minimizes ||q - (Rp + t)||^2
    in:
        q   dxn np.array (d is 2D or 3D)
        p   dxn np.array
    out:
        (R, t)  SE(d) rigid body transformation
    """
    assert q.shape[0] == p.shape[0]
    assert q.shape[1] == p.shape[1]
    assert q.shape[1] > 0

    d, n = q.shape

    # shift point clouds by centroids
    mu_q = q.mean(1)
    mu_p = p.mean(1)
    Q = q - np.tile(mu_q, (n, 1)).T
    P = p - np.tile(mu_p, (n, 1)).T


    # construct H matrix (dxd)
    H = np.matmul(Q, P.T)

    # perform SVD of H
    U, _, Vt = np.linalg.svd(H, full_matrices=True, compute_uv=True)
    D = np.eye(d)
    D[d-1,d-1] = np.linalg.det(np.matmul(U, Vt))

    # solve rotation-only problem
    R = np.matmul(np.matmul(U, D), Vt)

    # solve translation
    t = mu_q - np.matmul(R, mu_p)

    return R, t
```

(from [aclswarm](https://github.com/mit-acl/aclswarm/blob/master/aclswarm/src/aclswarm/assignment.py#L15))
