### ISSUE TITLE
Could not open the PLY file

### ISSUE THREAD

**Issue by hwcao17** [mit-acl/clipper#2]
Hi, Thanks for opening great work. I tried to run the python example but I got the error "[Open3D WARNING] Read PLY failed: unable to open file: ../data/bun1k.ply" and the number of points in the point cloud was zero.  I tested with another irrelevant PLY file and open3d just worked fine.  Are there any suggestions to fix the problem?

**Comment by hwcao17** [comment]
I solved it. Sorry for the bother.

**Comment by plusk01** [comment]
Hi @intrepidChw, thanks for reaching out. Was the issue that `python3 -m notebook` was run in `clipper/examples/python` instead of `clipper/examples`, making it so the `data` directory could not be seen?

thanks and feel free to reopen / create new issue if problems arise
