### ISSUE TITLE
about setting weights for M_{ii} based on descriptor similarity

### ISSUE THREAD

**Issue by Weixin-Ma** [mit-acl/clipper#20]
Hello there,

Many thanks for open-soure this very nice work. I really enjoy reading your papers. 

I am wondering whether the current version of CLIPPER in this repository supports setting weights for M_{ii} based on descriptor similarity instead of setting as "1". I try to simply add such weights (range: [0,1]) by the following code (but it works pretty bad, resulting in many repeated items in the clique): 

```C++

void CLIPPER::scorePairwiseConsistency_withweight(const invariants::Data& D1,const invariants::Data& D2,const std::vector<double>& weights, const Association& A)
{
  if (A.size() == 0) A_ = utils::createAllToAll(D1.cols(), D2.cols());
  else A_ = A;
  
  const size_t m = A_.rows();
  
  Eigen::MatrixXd M = Eigen::MatrixXd::Zero(m, m);
  
  #pragma omp parallel for shared(A_, D1, D2, M_, C_) if(parallelize_)
  for (size_t k=0; k<m*(m-1)/2; ++k) {
    size_t i, j; std::tie(i, j) = utils::k2ij(k, m);
  
    if (A_(i,0) == A_(j,0) || A_(i,1) == A_(j,1)) {
      // violates distinctness constraint
      continue;
    }

  //
  // Evaluate the consistency of geometric invariants associated with ei, ej
  //

  // points to extract invariant from in D1
  const auto& d1i = D1.col(A_(i,0));
  const auto& d1j = D1.col(A_(j,0));

  // points to extract invariant from in D2
  const auto& d2i = D2.col(A_(i,1));
  const auto& d2j = D2.col(A_(j,1));

  const double scr = (*invariant_)(d1i, d1j, d2i, d2j);
  if (scr > params_.affinityeps) { // does not violate inconsistency constraint
    M(i,j) = scr;
  }
  }
  
  //**************** for diagonal weights
  for (int i = 0; i < weights.size(); ++i)
  {
    M(i,i) = weights[i];
    // std::cout<<"weights["<<i<<"] = "<<weights[i]<<std::endl;
  }
 //****************
    
  // Identity on diagonal is taken care of implicitly in findDenseClique()
  // M += Eigen::MatrixXd::Identity(m, m);
  
  M_ = M.sparseView();
  
  C_ = M_;
  C_.coeffs() = 1;
}


int main(int argc, char **argv){
  clipper::invariants::EuclideanDistancePtr invariant =
            std::make_shared<clipper::invariants::EuclideanDistance>(iparams);

  clipper::Params params;
  clipper::CLIPPER clipper(invariant, params);

  //
  // Identify data association
  //

  clipper::Association A = clipper::Association(association_num, 2);
  for (int i = 0; i < association_num; i++) {
    A(i, 0) = i;
    A(i, 1) = i;
  }


  //get model, data, weights
  ... 

 clipper.scorePairwiseConsistency_withweight(model, data,weights, A);  

  // find the densest clique of the previously constructed consistency graph
  clipper.solve();
}
```

Could you please give me some suggestions about how to correctly set weights for diagonal weights? Considering such diagonal weights are quite different from non-diagonal weights (EuclideanDistance based in CLIPPER), do we need to scale the diagonal weights to handel such difference?

Thanks and regards,

weixin

**Comment by plusk01** [comment]
hi @Weixin-Ma , thanks for the kind words and your interest in our work.

Currently, the code assumes the diagonal of `M` is all ones. This was done for efficiency reasons in https://github.com/mit-acl/clipper/pull/5.

In your code you have removed that assumption in the creation of the affinity matrix, but not in the optimization. Check out the changes to `findDesnseClique` in this commit https://github.com/mit-acl/clipper/pull/5/commits/a899d44a76e101d7b4908ee25a5b445048b8f165#. For example 

```
Eigen::VectorXd u = M * u0;
```

was changed to 

```
Eigen::VectorXd u = M_.selfadjointView<Eigen::Upper>() * u0 + u0;
```

where the `+ u0` was added bc we implicitly assume `M` _should have_ ones on the diagonal, but the actual implementation of `M` has zeros on the diagonal.

The other changes in that function have a similar assumption and would need to be changed to support an arbitrary diagonal.

I know @mbpeterson70 has also been interested in encoding self-similarity along the diagonal

**Comment by Weixin-Ma** [comment]
HI @plusk01, many thanks for your suggestions. 

I tested the old version of clipper before changes added in commit [a899d44](https://github.com/mit-acl/clipper/commit/a899d44a76e101d7b4908ee25a5b445048b8f165). It works, while the speed is much slower as you mentionded. 

I also interestingly found that such weights seems have limited influence to the final clique. I tired `cosine similarity`, `normalized cosine similarity (among all the diagonal)`, all `0.2`, all `0.5`, and all `1`. The clique results are highly consistent, only few associations(1 - 2) among results are different (in my case, missing). Could you please share some insights about the possible reasons according to your experience?

Thanks and regards,
weixin

**Comment by mbpeterson70** [comment]
Hi @Weixin-Ma, it sounds like you're running into something similar to what some of my recent work has found as well. The issue is that if you look at the numerator of the maximum clique optimization (`u.T @ M @ u`), the diagonal elements actually have a very limited impact on the selected associations. In fact, the impact diminishes as the number of selected inlier associations increases since if you expand the optimization you get: `(u_i^2 * m_ii for each inlier i) + (u_i * u_j * m_ij for each inlier i and j, i != j)`. If there are more than just a few inliers, `m_ii` plays a very limited role.

We found that taking the weighted geometric mean of the pairwise association similarity score with each point-to-point similarity scores produces much better results. So if you have an association a and b we set each element of the affinity matrix M to `(pairwise_affinity_score(a, b)^w * point_similarity_score(a) * point_similarity_score(b))^(1/(w+2)))`. 

Our [recent RSS workshop paper](https://nature-bots.github.io/assets/camera-ready/Outdoor-localization_Mason.pdf) goes into more detail and we are planning on releasing code in a couple weeks for this as well!

**Comment by Weixin-Ma** [comment]
Hi @mbpeterson70, many thanks for your nice and detailed explanation. I also enjoy reading your RSS workshop paper, which gives me many new insights. Look forward to the future released code.

Hi @plusk01, many thanks again for your quick reply.

**Comment by mbpeterson70** [comment]
@Weixin-Ma thanks a lot! I'll be sure to update this issue when the code is released!
