### ISSUE TITLE
How to uninstall clipper safely

### ISSUE THREAD

**Issue by songanz** [mit-acl/clipper#6]
Hi, I would like to know how to uninstall clipper safely. I have installed the python bindings and I would like to uninstall it.

**Comment by plusk01** [comment]
hi @songanz, clipper uses `cmake` for building, which [does not support a `make uninstall` command](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake). You can remove files yourself after a `make install` by removing the files in the automatically created `install_manifest.txt` (e.g., see [this](https://stackoverflow.com/a/66704096/2392520) stackoverflow answer).

If you just want to remove the python bindings that were installed after running `make pip-install`, you can uninstall the `clipper` python package as you would any other python package --- `pip uninstall clipper`.

Note that with clipper version 0.2, the python package was renamed to `clipperpy`, so the command would be `pip uninstall clipperpy`. You can quickly check which version you have using `pip list | grep clipper`. For example, on my machine I have

```bash
$ python3 -m pip list | grep clipper
clipperpy                     0.2
```
