### ISSUE TITLE
Invariant choices

### ISSUE THREAD

**Issue by songanz** [mit-acl/clipper#7]
Hi,

Thanks for your great work! I have a question regarding the invariant choices. I am using the python API and cannot find a documentation that list different invariant choices. 

Right now I am using this `clipper.invariants.EuclideanDistanceParams()` as in the tutorial. Is there any other already implemented invariant? I know we can implement ourselves.

**Comment by songanz** [comment]
And also, if I don't know the _A_ matrix, how should I use the `score_pairwise_consistency()` function? Right now I am just generate a random _A_ matrix.

**Comment by plusk01** [comment]
hi, currently there are only two invariants implemented in this repo: `EuclideanDistance` and `PointNormalDistance`. The `PointNormalaDistance` invariant has [four parameters](https://github.com/mit-acl/clipper/blob/main/include/clipper/invariants/pointnormal_distance.h#L27), two for the point distance comparison and two for the normal distance (angle between normal vectors) comparison. This invariant can be used for data association between two point clouds with normals, or for matching planar patches. However, in the planar patch case, this distance isn't truly "invariant" --- e.g., if the patch is extracted with different areas between the two views, the center point of the patch will be different.

I've recently solved this issue by leveraging a manifold representation of planes with a new invariant. This invariant is not implemented here yet.

Another invariant I have used (although not yet implemented here) is a three-way invariant for data association between two point clouds with unknown scales.

If you don't have an initial set of correspondence guesses, you may use an all-to-all hypothesis `clipperpy.utils.create_all_to_all()` (or simply omit the `A` parameter from `score_pairwise_consistency()`). However, in this case you must be wary of how many potential associations will be evaluated. In the all-to-all case, the problem size is n choose 2. CLIPPER is efficient ([2000 associations takes 130 ms](https://github.com/mit-acl/clipper/pull/5)), but these graph-based methods tend to scale poorly as the number of associations grows. It is best to use some information (descriptors, color, intensity, etc) to create a set of initial guesses; it's okay if many of them are bad, as long as there is some set of good initial associations, CLIPPER can find them.
