### ISSUE TITLE
make error with matlab bindings

### ISSUE THREAD

**Issue by HuanYin94** [mit-acl/clipper#8]
Thanks for the good work. Very interesting and impressive!

I want to compile with Matlab bindings, and have the issue as follows,

**cmake .. -DBUILD_BINDINGS_MATLAB=ON** is succeed

![image](https://user-images.githubusercontent.com/7781990/178671223-781fdd73-f284-4a23-b10f-fd7271165477.png)

but after that, **make** has an error

![image](https://user-images.githubusercontent.com/7781990/178671478-7716583a-d7f1-4005-9a31-add9ad93be0d.png)

**Comment by plusk01** [comment]
Hi @HuanYin94, thanks for your interest. Unfortunately I recently made some changes to speed up the algorithm which broke the MATLAB bindings. Until I get a chance to fix it, you may use the Python bindings or you can use an older version of the code which should have working MATLAB bindings. Try this commit, for example: f4e67ec575a2d4d505971ac2ab15fd2208b3a193

**Comment by HuanYin94** [comment]
> Hi @HuanYin94, thanks for your interest. Unfortunately I recently made some changes to speed up the algorithm which broke the MATLAB bindings. Until I get a chance to fix it, you may use the Python bindings or you can use an older version of the code which should have working MATLAB bindings. Try this commit, for example: [f4e67ec](https://github.com/mit-acl/clipper/commit/f4e67ec575a2d4d505971ac2ab15fd2208b3a193)

I see. Thanks for your prompt reply.

**Comment by JereKnuutinen** [comment]
Hi, I cloned the commit f4e67ec and builded it. However I am now gettingthe following error in Matlab: Unrecognized function or variable 'clipper_pointnormaldistance'.
